FROM python:3.11-slim
WORKDIR /app
COPY pyproject.toml requirements.txt README.md ./
COPY app ./app
COPY config ./config
COPY alembic.ini ./
COPY alembic ./alembic
RUN pip install --no-cache-dir -e .
CMD ["uvicorn", "app.api.main:app", "--host", "0.0.0.0", "--port", "8000"]
