FROM python:3.11-slim
WORKDIR /app
COPY pyproject.toml requirements.txt README.md ./
COPY app ./app
COPY config ./config
RUN pip install --no-cache-dir -e .
CMD ["celery", "-A", "app.workers.celery_app", "worker", "-l", "info"]
